export interface Prompt {
  project_id: string | null;
  level: number | null;
  row_id: string;
  parent_row_id: string | null;
  prompt_name: string;
  note: string | null;
  created: string;
  is_deleted: boolean;
  admin_prompt_result: string | null;
  user_prompt_result: string | null;
  input_admin_prompt: string | null;
  input_user_prompt: string | null;
  model: string | null;
  model_on: boolean;
  temperature: number | null;
  temperature_on: boolean;
  max_tokens: number | null;
  max_tokens_on: boolean;
  top_p: number | null;
  top_p_on: boolean;
  frequency_penalty: number | null;
  frequency_penalty_on: boolean;
  presence_penalty: number | null;
  presence_penalty_on: boolean;
  stop: string[] | null;
  stop_on: boolean;
  n: number | null;
  n_on: boolean;
  logit_bias: Record<string, number> | null;
  logit_bias_on: boolean;
  o_user: string | null;
  o_user_on: boolean;
  stream: boolean;
  stream_on: boolean;
  best_of: number | null;
  best_of_on: boolean;
  logprobs: number | null;
  logprobs_on: boolean;
  echo: boolean;
  echo_on: boolean;
  suffix: string | null;
  suffix_on: boolean;
  temperature_scaling: number | null;
  temperature_scaling_on: boolean;
  prompt_tokens: number | null;
  prompt_tokens_on: boolean;
  response_tokens: number | null;
  response_tokens_on: boolean;
  batch_size: number | null;
  batch_size_on: boolean;
  learning_rate_multiplier: number | null;
  learning_rate_multiplier_on: boolean;
  n_epochs: number | null;
  n_epochs_on: boolean;
  validation_file: string | null;
  validation_file_on: boolean;
  training_file: string | null;
  training_file_on: boolean;
  engine: string | null;
  engine_on: boolean;
  input: string | null;
  input_on: boolean;
  context_length: number | null;
  context_length_on: boolean;
  custom_finetune: string | null;
  custom_finetune_on: boolean;
  prompt_settings_open: boolean;
  src_admin_prompt_result: Record<string, any> | null;
  src_user_prompt_result: Record<string, any> | null;
  src_input_admin_prompt: Record<string, any> | null;
  src_input_user_prompt: Record<string, any> | null;
  src_note: Record<string, any> | null;
  response_format: Record<string, any> | null;
  response_format_on: boolean;
  source_info: Record<string, any> | null;
  highlights: Record<string, any> | null;
}