-- Add model and settings columns to cyg_prompts table
ALTER TABLE public.cyg_prompts
ADD COLUMN IF NOT EXISTS model text,
ADD COLUMN IF NOT EXISTS model_on boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS temperature text,
ADD COLUMN IF NOT EXISTS temperature_on boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS max_tokens text,
ADD COLUMN IF NOT EXISTS max_tokens_on boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS top_p text,
ADD COLUMN IF NOT EXISTS top_p_on boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS frequency_penalty text,
ADD COLUMN IF NOT EXISTS frequency_penalty_on boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS presence_penalty text,
ADD COLUMN IF NOT EXISTS presence_penalty_on boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS stop text,
ADD COLUMN IF NOT EXISTS stop_on boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS n text,
ADD COLUMN IF NOT EXISTS n_on boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS logit_bias text,
ADD COLUMN IF NOT EXISTS logit_bias_on boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS o_user text,
ADD COLUMN IF NOT EXISTS o_user_on boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS stream boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS stream_on boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS best_of text,
ADD COLUMN IF NOT EXISTS best_of_on boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS logprobs text,
ADD COLUMN IF NOT EXISTS logprobs_on boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS echo boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS echo_on boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS suffix text,
ADD COLUMN IF NOT EXISTS suffix_on boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS response_format text,
ADD COLUMN IF NOT EXISTS response_format_on boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS context_length text,
ADD COLUMN IF NOT EXISTS context_length_on boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS settings_expanded boolean DEFAULT false;